# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Remote' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'BetterSegmentedControl', '~> 1.0'
  use_frameworks!

  # Pods for Remote

  target 'RemoteTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RemoteUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
